//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUIZLANG_Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int TestHistoryID { get; set; }
        public System.DateTime time { get; set; }
        public int userID { get; set; }
        public int result { get; set; }
        public string nativeLanName { get; set; }
        public string learntLanName { get; set; }
    }
}
