//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUIZLANGEntities : DbContext
    {
        public QUIZLANGEntities()
            : base("name=QUIZLANGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Directory> Directory { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<TestTemp> TestTemp { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
