//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTemp
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string QuestionWord { get; set; }
        public string AnswerWord { get; set; }
    }
}
